name: Docker Image CI

env:
  HUGO_VERSION: "0.55.5"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Registry
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN

      - name: Building Docker Image
        env:
          CONTAINER_IMAGE_NAME: ${{ secrets.CONTAINER_IMAGE_NAME }}
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_USERNAME }}
          HUGO_VERSION: ${{ secrets.SECRET_KEY }}
        run: docker build --build-arg HUGO_VERSION=$HUGO_VERSION
          --no-cache -t $DOCKER_USERNAME/$CONTAINER_IMAGE_NAME:latest .

      - name: Push Docker Container to Registry
        env:
          CONTAINER_IMAGE_NAME: ${{ secrets.CONTAINER_IMAGE_NAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker push $DOCKER_USERNAME/$CONTAINER_IMAGE_NAME:latest
