name: Docker Image CI

env:
  HUGO_VERSION: "0.55.5"
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REGISTRY: docker.pkg.github.com

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Registry
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN $DOCKER_REGISTRY

      - name: Building Docker Image
        run: docker build --build-arg HUGO_VERSION=$HUGO_VERSION --no-cache
          -t $DOCKER_REGISTRY/$GITHUB_REPOSITORY/hugo-docker:$HUGO_VERSION-$GITHUB_RUN_ID
          -t $DOCKER_REGISTRY/$GITHUB_REPOSITORY/hugo-docker:latest .

      - name: Push Docker Container to Registry
        run: docker push $DOCKER_REGISTRY/$GITHUB_REPOSITORY/hugo-docker
